version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: bandodok/devops-for-programmers-project-lvl1
    command: npm test
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file: ./app/.env
    environment:
      POSTGRES_PASSWORD: $${DATABASE_PASSWORD}
      POSTGRES_USERNAME: $${DATABASE_USERNAME}