version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"

  caddy:
    image: caddy:alpine
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app